data_dir="data/trialReport/ReportQL/dataset" # path for data files
schema_path="data/trialReport/ReportQL/Schemas/organs/simpleSchema.json"
output_dir="output" # path to save the checkpoints
model_name_or_path='razent/SciFive-base-Pubmed_PMC'
tokenizer_name_or_path='razent/SciFive-base-Pubmed_PMC'
max_seq_length=350
min_length=250
num_beams=5
learning_rate=0.001
weight_decay=0.0
adam_epsilon=1e-8
warmup_steps=10000
train_batch_size=8
finetune_batch_size=8
eval_batch_size=8
num_train_epochs=50
gradient_accumulation_steps=8
gradient_checkpointing=true
do_lower_case=true
task='finetune'
n_gpu=1
# early_stop_callback=False
precision=32
backend="native"
max_grad_norm=1.0
seed=42
num_worker=6
repo_url="https://huggingface.co/sarme/ReportQL-base"
checkpoint=''
